config/routes.rb
Rails.application.routes.draw do
  root 'search#new'

  resource :search, only: [:new, :show], controller: 'search' do
    get 'load_tags', on: :collection
  end

  resources :dashboard, only: [:index]

  resources :templates, only: [:new, :create] do
    member do
      get 'details'
    end
  end

  resources :images, only: [:index, :destroy] do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :template_repos, only: [:index, :create, :destroy] do
    member do
      post 'reload'
    end
  end

  resources :registries, only: [:index, :create, :destroy, :update]

  resources :deployment_targets, only: [:index, :create, :destroy] do
    get :select, on: :collection
    get :token, on: :member
    resources :deployments, only: [:new, :create, :index, :show, :destroy] do
      post :redeploy, on: :member
    end
    resources :deployment_target_metadata_refreshes, only: :create, as: :metadata_refreshes
  end

  resources :jobs, param: :key, only: [:create, :new, :show, :destroy] do
    get :log, on: :member
  end

  resource :user, only: [:update]

  resources :apps, only: [:index, :create, :show, :update, :destroy] do
    member do
      get 'documentation'
      get 'journal'
      get 'relations'
      put 'rebuild'
      post 'template'
      get 'compose_yml'
      get 'compose_download'
      get 'compose_export'
    end
    resources :services, only: [:index, :update, :create, :show, :destroy] do
      get 'journal', on: :member
    end
    resources :categories, only: [:update, :create, :destroy] do
      put 'remove_service', on: :member
      post 'add_service', on: :member
    end
  end

  resources :host_health, only: [:index]

  resources :service_health, only: [:show], :id => /[^\/]+/

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  mount CtlBaseUi::Engine => '/ctl-base-ui'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  respond_to :html, except: :load_tags
  respond_to :json

  def new
    @search_result_set = SearchResultSet.new
    @keywords_sorted_by_term = Keyword.all_sorted_by(:keyword)
    @keywords_sorted_by_count = Keyword.all_sorted_by(:count).reverse
  end

  def show
    @search_result_set = SearchResultSet.find(params: params[:search_result_set])
    respond_with @search_result_set
  end

  def load_tags
    repository = Repository.find(
      params[:repo], params: { registry_id: params[:registry_id], local: params[:local_image] })

    respond_with repository.image_tags
  end
end

app/views/search/_absolute_image_row.html.haml
- remote ||= false
- app ||= nil
.search-result-item.absolute-image-result{data: {'title' => presenter.title, 'status-label' => presenter.status_label}}
  .badge.absolute= 'Absolute'
  .basic-info
    %h3
      = presenter.title
    %p
      This image search query looks like it may be a private image.
      %br/
      = link_to 'Learn about private image authorization.', 'https://github.com/CenturyLinkLabs/panamax-ui/wiki/How-to:-Add-Registries', target: '_blank'
  .actions
    - if app
      = form_tag app_services_path(app.id) do
        = hidden_field_tag 'app[name]', @app.name
        = hidden_field_tag 'app[category]', 'null', class: 'category-form-field'
        = hidden_field_tag 'name', presenter.title
        = hidden_field_tag 'app[image]', presenter.title
        %button.button-positive{ data: { disable_with: 'Adding...', tracking: { method: 'click', action: 'Add to Application', category: 'Run Image', label: presenter.title }}} Add to App
    - else
      = form_tag apps_path do
        = hidden_field_tag 'app[image]', presenter.title
        %button.button-positive{ data: { disable_with: 'Starting App...', tracking: { method: 'click', action: 'Create Application', category: 'Run Image', label: presenter.title }}} Run Image

app/views/search/_blog_item.html.haml
%li
  %span.timestamp {{timestamp}}
  %a{href: '{{link}}', target: '_new'}
    {{title}}

app/views/search/_examples.html.haml
%p.microcopy
  %strong Examples:
  Wordpress,
  =link_to '!=namespace/private-repo', 'https://github.com/CenturyLinkLabs/panamax-ui/wiki/How-to:-Add-Registries#running-an-image-from-a-private-repository', target: '_blank', title: 'Learn about search filters.'
  =','
  =link_to '!=your_registry_endpoint/your-repo', 'https://github.com/CenturyLinkLabs/panamax-ui/wiki/How-to:-Add-Registries#running-an-image-from-a-private-repository', target: '_blank', title: 'Learn about search filters.'
  =','
  Rails, redis, NGiNX, you get the picture...

app/views/search/_image_row.html.haml
- remote ||= false
.search-result-item.image-result{data: {'title' => presenter.title, 'status-label' => presenter.status_label}}
  .badge{class: presenter.badge_class}
    = presenter.status_label
  .basic-info
    %h3
      - if remote
        = link_to presenter.title, presenter.docker_index_url, target: '_blank', title: 'View details on the Docker Hub', class: 'docker-hub'
        = link_to presenter.title, presenter.imagelayers_url, target: '_blank', title: 'Inspect this image on imagelayers.io', class: 'imagelayers-link'
      - else
        = presenter.title
    %p= presenter.short_description
  .actions
    = form_tag apps_path do
      = hidden_field_tag 'app[image]', presenter.title
      = hidden_field_tag 'app[registry_id]', presenter.registry_id
      = label 'app[tag]', 'Tag:'
      = select_tag 'app[tag]',
        remote ? options_for_select(['latest']) : presenter.tag_options,
        id: nil,
        class: 'image-tag-select',
        data: { 'load-tags-endpoint' => load_tags_search_path, 'loaded' => !remote, 'registry-id' => presenter.registry_id }
      %button.button-positive{ data: { disable_with: 'Starting App...', tracking: { method: 'click', action: 'Create Application', category: 'Run Image', label: presenter.title }}} Run Image
  - if remote
    .community-data
      = link_to presenter.docker_index_url + "/stars/", target: '_blank' do
        .star-count=presenter.star_count

app/views/search/_keyword_cloud.html.haml
- show_selector =  "#sorted_by_#{sort_title.downcase}"
- display_style ||= 'block'
%section.example-searches.collapsed{style: "display: #{display_style};", id: "sorted_by_#{sorted_by}"}
  %h3
    Or, browse these available templates:
    %a{href: show_selector, data: { accordian: { expand: show_selector, collapse: '.example-searches' }}}= "Sort Searches by #{sort_title}"
  .keyword-bank
    - keywords.each do |kw|
      %a.keyword{data: {query: kw.keyword}}= "#{kw.keyword} (#{kw.count})"
  %a.toggler{data: { toggle: { target: '.example-searches', class: 'collapsed' }}}
    %span Show all keywords
    %span Show fewer keywords

app/views/search/_loading_row.html.haml
.search-result-item.in-progress
  .badge
  .basic-info
    %p
      = '{{loading_copy}}'
      %span.l-one>= '.'
      %span.l-two>= '.'
      %span.l-three= '.'

app/views/search/_modal_image_row.html.haml
- remote ||= false
.search-result-item.image-result{data: {'title' => presenter.title, 'status-label' => presenter.status_label}}
  .badge= presenter.status_label
  .basic-info
    %h3
      - if remote
        = link_to presenter.title, presenter.docker_index_url, target: '_blank', title: 'View details on the Docker Hub', class: 'docker-hub'
        = link_to presenter.title, presenter.imagelayers_url, target: '_blank', title: 'Inspect this image on imagelayers.io', class: 'imagelayers-link'
      - else
        = presenter.title
    %p= presenter.short_description
  .actions
    = form_tag app_services_path(@app.id) do
      = hidden_field_tag 'app[name]', @app.name
      = hidden_field_tag 'app[category]', 'null', class: 'category-form-field'
      = hidden_field_tag 'name', presenter.title
      = label 'app[tag]', 'Tag:'
      = select_tag 'app[tag]',
        remote ? options_for_select(['latest']) : presenter.tag_options,
        id: nil,
        class: 'image-tag-select',
        data: {'load-tags-endpoint' => load_tags_search_path, 'loaded' => !remote}
      %button.button-positive{ data: { disable_with: 'Adding...', tracking: { method: 'click', action: 'Add to Application', category: 'Run Image', label: presenter.title }}} Add to App
  - if remote
    .community-data
      = link_to presenter.docker_index_url + "/stars/", target: '_blank' do
        .star-count=presenter.star_count

app/views/search/_no_results_row.html.haml
.search-result-item.no-results
  .badge
  .basic-info
    %p
      %strong We're sorry, we couldn't find a template that was a good match.
      %br/
      Please select an appropriate base image from the results below, or try a new search.

app/views/search/_source_blurb_row.html.haml
- unless TemplateRepo.has_user_sources?
  .search-result-item.source-repo-blurb
    .badge
    .basic-info
      %p
        %strong Did you know you can create your own custom templates to use within Panamax?
    .link-actions
      = link_to 'Learn more', 'https://github.com/CenturyLinkLabs/panamax-ui/wiki/How-To:-Make-a-Template', target: '_blank'

app/views/search/_template_row.html.haml
.search-result-item.template-result{ id: "template_#{presenter.id}" }
  .badge
    %div
      %img{src: presenter.icon_src}
    = presenter.status_label
  .basic-info
    %h3
      = presenter.title
      = link_to 'Inspect template on imagelayers.io', presenter.imagelayers_url, class: 'imagelayers-link'
    %p
      = presenter.short_description
      %a{href:"/templates/#{presenter.id}/details", class: "template-details-link" } More Details
    %p.microcopy= "Source Last Refreshed: #{presenter.last_updated_on} UTC"
  .actions
    = form_tag apps_path do
      = hidden_field_tag 'app[template_id]', presenter.id
      .select-target-container
        .select-target{ data: { toggle: { class: 'expanded' } } }
          %header
            Run Template
          .target-options
            %ul
              %li
                %button.link{ data: { loading: 'Starting App...', tracking: { method: 'click', action: 'Create Application', category: 'Run Template', label: presenter.title }}} Run Locally
              %li
                = link_to 'Deploy to Target', "#{select_deployment_targets_path}?resource_id=#{presenter.id}&resource_type=Template", class: 'select-deployment-target'
  .community-data
    .image-count
      %em= presenter.image_count
      = presenter.image_count_label

app/views/search/new.html.haml
:ruby
  json_image_presenter = JsonImagePresenter.new
  content_for(:title, 'Search')
  content_for(:body_id, 'search_flow')

%script#template_result_template{type: 'text/x-handlebars-template'}
  = render 'template_row', {presenter: JsonTemplatePresenter.new}
%script#remote_image_result_template{type: 'text/x-handlebars-template'}
  = render 'image_row', {presenter: json_image_presenter, remote: true}
%script#local_image_result_template{type: 'text/x-handlebars-template'}
  = render 'image_row', {presenter: json_image_presenter}
%script#absolute_image_result_template{type: 'text/x-handlebars-template'}
  = render 'absolute_image_row', {presenter: json_image_presenter}
%script#loading_row_template{type: 'text/x-handlebars-template'}
  = render 'loading_row'
%script#no_results_row_template{type: 'text/x-handlebars-template'}
  = render 'no_results_row'
%script#source_blurb_row_template{type: 'text/x-handlebars-template'}
  = render 'source_blurb_row'
%script#blog_item_template{type: 'text/x-handlebars-template'}
  = render 'blog_item'

.filterable-list
  %h1 Search Panamax Templates & Docker Repositories
  = form_for @search_result_set, url: search_path, method: :get, html: {class: 'search-form'} do |f|
    = f.text_field :q, placeholder: 'enter your query', accesskey: 's', class: 'query-field'
    = f.button 'Search', class: 'button-primary'
    = render 'examples'

  = render 'keyword_cloud', keywords: @keywords_sorted_by_term, sort_title: 'Count', sorted_by: :name, display_style: 'none'
  = render 'keyword_cloud', keywords: @keywords_sorted_by_count, sort_title: 'Name', sorted_by: :count

  %h3.search-title Templates
  .template-results

  %h3.search-title Images
  .local-image-results
  .remote-image-results

  #template-details-dialog

%section.blog-feed
  %h3 From the CenturyLink Labs Blog
  %ul.blog-feed-items{ data: { source: 'https://labs.ctl.io/feed' } }
  %a.blog-link{href: 'https://labs.ctl.io'}
    View more at https://labs.ctl.io

%section.compose-banner
  = link_to image_tag('pmx_compose_yml.jpg'), apps_path

app/views/search/show.html.haml
- content_for(:title, 'Search Results')
- content_for(:body_id, 'search_flow')

%h2= "Results for #{@search_result_set.q}"
%h3.search-title Templates
.template-results
  - @search_result_set.templates.each do |template|
    = render 'template_row', {presenter: TemplatePresenter.new(template)}
  = render 'source_blurb_row'
%h3.search-title Images
.local-image-results
  - @search_result_set.local_images.each do |image|
    = render 'image_row', {presenter: ImagePresenter.new(image, self)}
.remote-image-results
  - @search_result_set.remote_images.each do |image|
    = render 'image_row', {presenter: ImagePresenter.new(image, self), remote: true}