config/routes.rb
Rails.application.routes.draw do
  root 'search#new'

  resource :search, only: [:new, :show], controller: 'search' do
    get 'load_tags', on: :collection
  end

  resources :dashboard, only: [:index]

  resources :templates, only: [:new, :create] do
    member do
      get 'details'
    end
  end

  resources :images, only: [:index, :destroy] do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :template_repos, only: [:index, :create, :destroy] do
    member do
      post 'reload'
    end
  end

  resources :registries, only: [:index, :create, :destroy, :update]

  resources :deployment_targets, only: [:index, :create, :destroy] do
    get :select, on: :collection
    get :token, on: :member
    resources :deployments, only: [:new, :create, :index, :show, :destroy] do
      post :redeploy, on: :member
    end
    resources :deployment_target_metadata_refreshes, only: :create, as: :metadata_refreshes
  end

  resources :jobs, param: :key, only: [:create, :new, :show, :destroy] do
    get :log, on: :member
  end

  resource :user, only: [:update]

  resources :apps, only: [:index, :create, :show, :update, :destroy] do
    member do
      get 'documentation'
      get 'journal'
      get 'relations'
      put 'rebuild'
      post 'template'
      get 'compose_yml'
      get 'compose_download'
      get 'compose_export'
    end
    resources :services, only: [:index, :update, :create, :show, :destroy] do
      get 'journal', on: :member
    end
    resources :categories, only: [:update, :create, :destroy] do
      put 'remove_service', on: :member
      post 'add_service', on: :member
    end
  end

  resources :host_health, only: [:index]

  resources :service_health, only: [:show], :id => /[^\/]+/

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  mount CtlBaseUi::Engine => '/ctl-base-ui'
end

app/views/templates/_form.html.haml
%h3 Information retrieved from GitHub
%dl
  %dt Username:
  %dd= template_form.user.github_username
  %dt Email Address:
  %dd= template_form.user.email

%p
  = link_to "Replace GitHub Token", '#', id: 'token-replace'

#update-token-modal
  = render 'github_token_replace', user: @user

= form_for template_form, url: templates_path do |f|
  = f.hidden_field :app_id
  %h3 Select a repository for your application template
  = f.select :repo, options_for_select(template_form.user.repositories), {}, class: 'fancy'

  or,
  = link_to 'create a new Github repo', 'https://github.com/new', target: '_blank'

  %h3 Add some information about your template to help others find it in search results

  %dl
    %dt= f.label :name, 'Template Name', class: 'required'
    %dd= f.text_field :name, placeholder: 'Give your template a name'
    %dt= f.label :author, 'Template Author'
    %dd= f.text_field :author
    %dt= f.label :description, 'Template Description'
    %dd= f.text_area :description, placeholder: 'Give your template a description'
    %dt= f.label :keywords, class: 'optional'
    %dd= f.text_field :keywords, placeholder: 'Add some keywords, seperated by commas'
    %dt.optional Template Icon
    %dd.template-icons
      - f.object.types.each do |type|
        = label_tag do
          = f.radio_button :type, type.name
          = image_tag icon_source_for(type.name)
          %span= type.name

  %h3 Template Documentation
  %label.documentation
    %div
      %strong
        Add some instructions to help people use your template. Check out some
        = succeed '.' do
          %a{href: 'https://github.com/CenturyLinkLabs/panamax-ui/wiki/How-To:-Create-Template-Documentation', target: '_blank'} examples

    Confused about the syntax?
    = link_to 'See the markdown guide here', 'http://daringfireball.net/projects/markdown/syntax', target: '_blank'
    = f.text_area :documentation, class: 'template_documentation'

  - tracking_hash = { tracking_method: 'click', tracking_category: 'Create Template', tracking_action: 'Initiate Save Template', tracking_label: template_form.app.try(:name) }
  = button_tag 'Publish Your Template', class: 'button-positive', data: tracking_hash
  = button_tag 'Preview Template File', type: 'button', class: 'button-secondary preview', data: { previewPath: template_app_path(template_form.app_id) }

app/views/templates/_github_token_form.html.haml
%h3 First, you'll need to create a github token
%p
  Visit
  = link_to 'Generate a Github access token', 'https://github.com/settings/tokens/new?scope=repo,user:email', target: '_blank'

= form_for user, url: user_path, method: :put, html: { class: 'update-github-token' } do |f|
  %strong
    = f.label :github_access_token, 'Github Token'
  = f.text_field :github_access_token, placeholder: 'Paste your GitHub token here'
  %label.subscribe-flag
    = f.check_box :subscribe, {}, true, false
    Sign up for our newsletter - Get all the latest news, tips & tricks for Panamax
  = f.button 'Save Token', class: 'button-positive'

app/views/templates/_github_token_replace.html.haml
%p
  Make sure your token is scoped to 'repo' and 'user'.  You can regenerate your token at
  = link_to 'https://github.com/settings/applications', 'https://github.com/settings/applications', target: '_blank'

= form_for user, url: user_path, method: :put, html: { class: 'update-github-token' } do |f|
  %strong
    = f.label :github_access_token, 'GitHub Token'
  = f.text_field :github_access_token, placeholder: 'Paste your GitHub token here'

app/views/templates/details.html.haml
- content_for(:title, 'Template Details')
.template-images
  %h2 Template Images
  %ul
    - @template.images.each do |image|
      %li.template-image-detail
        .template-image-icon
          %img{src: image.icon}
        = image.source
        .template-image-external
          = link_to 'View on Docker Hub', image.docker_index_url, target: '_blank'
          = link_to 'Inspect on imagelayers.io', "#{@template.imagelayers_url}&lock=#{image.source}", class: 'imagelayers-link-with-text', target: '_blank'
- if @template.documentation
  %h2 Documentation

  #post-run-html
    = @template.documentation_to_html.html_safe

app/views/templates/new.html.haml
- content_for(:title, 'Save as Template')
- content_for(:body_id, 'template_flow')

= render 'shared/errors', errors: @template_form.errors

%h1= yield(:title)
- if @user.has_valid_github_creds?
  = render 'form', template_form: @template_form

- else
  = render 'github_token_form', user: @user