config/routes.rb
Rails.application.routes.draw do
  root 'search#new'

  resource :search, only: [:new, :show], controller: 'search' do
    get 'load_tags', on: :collection
  end

  resources :dashboard, only: [:index]

  resources :templates, only: [:new, :create] do
    member do
      get 'details'
    end
  end

  resources :images, only: [:index, :destroy] do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :template_repos, only: [:index, :create, :destroy] do
    member do
      post 'reload'
    end
  end

  resources :registries, only: [:index, :create, :destroy, :update]

  resources :deployment_targets, only: [:index, :create, :destroy] do
    get :select, on: :collection
    get :token, on: :member
    resources :deployments, only: [:new, :create, :index, :show, :destroy] do
      post :redeploy, on: :member
    end
    resources :deployment_target_metadata_refreshes, only: :create, as: :metadata_refreshes
  end

  resources :jobs, param: :key, only: [:create, :new, :show, :destroy] do
    get :log, on: :member
  end

  resource :user, only: [:update]

  resources :apps, only: [:index, :create, :show, :update, :destroy] do
    member do
      get 'documentation'
      get 'journal'
      get 'relations'
      put 'rebuild'
      post 'template'
      get 'compose_yml'
      get 'compose_download'
      get 'compose_export'
    end
    resources :services, only: [:index, :update, :create, :show, :destroy] do
      get 'journal', on: :member
    end
    resources :categories, only: [:update, :create, :destroy] do
      put 'remove_service', on: :member
      post 'add_service', on: :member
    end
  end

  resources :host_health, only: [:index]

  resources :service_health, only: [:show], :id => /[^\/]+/

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  mount CtlBaseUi::Engine => '/ctl-base-ui'
end

app/models/deployment_target.rb
class DeploymentTarget < BaseResource

  schema do
    string :name
    string :auth_blob
    string :endpoint_url
  end

  class Metadata < BaseResource
    def created_at
      Time.parse(attributes[:created_at])
    end
  end
end

app/controllers/deployment_targets_controller.rb
class DeploymentTargetsController < ApplicationController
  respond_to :html
  respond_to :json, only: [:destroy]

  def index
    hydrate_index_view
    @deployment_target = DeploymentTarget.new
  end

  def select
    @resource = { type: params[:resource_type], id: params[:resource_id] }
    @deployment_targets = DeploymentTarget.all
    render layout: 'plain'
  end

  def create
    @deployment_target = DeploymentTarget.create(params[:deployment_target])
    if @deployment_target.valid?
      flash[:success] = I18n.t('deployment_targets.create.success')
      redirect_to deployment_targets_path
    else
      hydrate_index_view
      render :index
    end
  end

  def destroy
    target = DeploymentTarget.find(params[:id])
    respond_with(target.destroy, location: deployment_targets_path)
  end

  def token
    target = DeploymentTarget.find(params[:id])
    send_data target.auth_blob,
      filename: "#{sanitize_filename(target.name)}.txt",
      type: 'text/plain'
  end

  private

  def sanitize_filename(name)
    name.gsub(/[^0-9A-Za-z.\-]/, '_')
  end

  def hydrate_index_view
    @deployment_targets = DeploymentTarget.all
    @job_templates_by_vendor = JobTemplate.all.group_by(&:vendor)
    @jobs = Job.all
      .map(&:with_template!)
      .map(&:with_log!)
      .map(&:with_step_status!)
      .reverse
  end
end

app/views/deployment_targets/_deployment_target.html.haml
.deployment-target
  = link_to deployment_target.name,
            deployment_target_deployments_path(deployment_target),
            class: 'name'
  %em.status
    %span.last-updated
      Last Updated:
      - if deployment_target.metadata?
        = l(deployment_target.metadata.created_at, format: :informal)
      - else
        never
    = form_for DeploymentTargetMetadataRefresh.new, url: deployment_target_metadata_refreshes_path(deployment_target) do |f|
      = f.button "Refresh"
  .actions
    = link_to 'Delete Target',
              deployment_target_path(deployment_target),
              class: 'delete-action',
              title: 'delete',
              method: 'delete',
              data: { delete_confirm: 'Delete this Target?', delete_remove_at: '.deployment-target' }
  %dl.target-info
    %dt Endpoint:
    %dd= deployment_target.endpoint_url
    - if deployment_target.metadata?
      %dt Agent Version:
      %dd= deployment_target.metadata.agent_version
      %dt Adapter Type:
      %dd= deployment_target.metadata.adapter_type
      %dt Adapter Version:
      %dd= deployment_target.metadata.adapter_version
  %dl.token
    %dt{ data: { toggle: { class: 'expanded' } } }
      Target Token
    %dd.token-contents
      .token-container
        %div{ contenteditable: true }= deployment_target.auth_blob
    .actions
      %a{ data: { clipboard: { text: deployment_target.auth_blob, after: 'Token Copied to Clipboard' } } } Copy Token to Clipboard
      = link_to 'Download Token', token_deployment_target_path(deployment_target)

app/views/deployment_targets/_job.html.haml
%div{class: presenter.status}
  %h5
    %span= presenter.title
    %em.status-info= presenter.status
    = link_to 'Dismiss',
              presenter.destroy_path,
              class: 'delete-action',
              title: 'delete',
              method: 'delete',
              data: { delete_remove_at: '.deployment-job' }
    %a.toggle-log Toggle Log
  %ol
    = presenter.steps do |name, status|
      %li{ class: status }
        %strong= name
        %em.status-info= status
  %p.message= presenter.message

app/views/deployment_targets/index.html.haml
- content_for(:title, 'Remote Deployment Targets')
- content_for(:body_id, 'deployments_flow')
= render '/shared/breadcrumbs', breadcrumbs: ['Manage', yield(:title)]
%script#job_template{type: 'text/x-handlebars-template'}
  = render 'job', { presenter: JsonJobPresenter.new(self) }
%script#journal_line_template{type: 'text/x-handlebars-template'}
  %p
    %span.timestamp {{timestamp}}
    %span.source {{source}}
    {{message}}

- @jobs.each do |job|
  - presenter = JobPresenter.new(job, self)
  .deployment-job{ class: "initially-#{presenter.status}", id: "#{presenter.dom_id}" }
    .deployment-job-progress{ data: { source: job_path(job.key) } }
      = render 'job', presenter: presenter
    - if presenter.documentation.present?
      .deployment-job-documentation
        %h5 Documentation
        != presenter.documentation
    .deployment-job-log
      %code.log-output{ data: { source: log_job_path(job.key) } }
        - job.log.each do |output|
          %p= output

= render @deployment_targets

- if @jobs.empty? && @deployment_targets.to_a.empty?
  %p.macrocopy
    A Remote Deployment Target allows you to use Panamax to deploy templates and images to your infrastructure.
    You can setup your target manually and register it with Panamax via a token, or via Dray, leveraging popular cloud providers and orchestrators.
    %br/
    = link_to 'Learn more about Remote Deployment Targets.', 'https://github.com/CenturyLinkLabs/panamax-ui/wiki/Panamax-Remote-Agent-Installation', target: '_blank'
    %br/
    = link_to 'Learn more about Dray.', 'https://registry.hub.docker.com/u/centurylink/dray/', target: '_blank'

= render 'shared/errors', errors: @deployment_target.errors
= form_for @deployment_target, html: { id: 'create_target', class: ('expanded' unless @deployment_target.valid?) } do |f|
  %dl
    %dt= f.label :name
    %dd= f.text_field :name
    %dt= f.label :auth_blob, 'Token'
    %dd= f.text_area :auth_blob

  = f.button 'Save Remote Deployment Target', class: 'button-add-positive'
  %a.button-cancel{ { data: { toggle: { target: '#create_target', class: 'expanded' }, cancel: { form: true } } } }
    Cancel

.add-target
  %h2 Add a Remote Deployment Target
  .providers
    %p.macrocopy
      Automatically set up your deployment target on one of these providers using
      = link_to 'Dray.', 'https://registry.hub.docker.com/u/centurylink/dray/', target: '_blank'

    %ul
      - @job_templates_by_vendor.each do |vendor, templates|
        %li.provider
          %span= provider_label(vendor)
          .job-templates
            %h6 Select Orchestrator
            - templates.each do |job_template|
              = link_to job_template.adapter, new_job_path(template_id: job_template.id), title: job_template.name

    %p.alternative-provider
      Don't see your favorite provider listed?
      %br/
      Set a deployment target up manually.
      = link_to 'Learn more.', 'https://github.com/CenturyLinkLabs/panamax-ui/wiki/Panamax-Remote-Agent-Installation', target: '_blank'
  %p
    Already have a deployment target set up?
    %br/
    %a{ { data: { toggle: { target: '#create_target', class: 'expanded' } } } } Enter your token here.

app/views/deployment_targets/select.html.haml
- content_for(:title, 'Select Remote Target')
.select-remote-target
  %ul
    - @deployment_targets.each do |target|
      %li
        %dl
          %dt=target.name
          %dd
            Endpoint:
            = target.endpoint_url
        = link_to 'Select this Target', new_deployment_target_deployment_path(target, resource_id: @resource[:id], resource_type: @resource[:type]), class: 'button-positive'

  = link_to 'Add a New Remote Deployment Target', deployment_targets_path, class: 'button-add-positive'