config/routes.rb
Rails.application.routes.draw do
  root 'search#new'

  resource :search, only: [:new, :show], controller: 'search' do
    get 'load_tags', on: :collection
  end

  resources :dashboard, only: [:index]

  resources :templates, only: [:new, :create] do
    member do
      get 'details'
    end
  end

  resources :images, only: [:index, :destroy] do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :template_repos, only: [:index, :create, :destroy] do
    member do
      post 'reload'
    end
  end

  resources :registries, only: [:index, :create, :destroy, :update]

  resources :deployment_targets, only: [:index, :create, :destroy] do
    get :select, on: :collection
    get :token, on: :member
    resources :deployments, only: [:new, :create, :index, :show, :destroy] do
      post :redeploy, on: :member
    end
    resources :deployment_target_metadata_refreshes, only: :create, as: :metadata_refreshes
  end

  resources :jobs, param: :key, only: [:create, :new, :show, :destroy] do
    get :log, on: :member
  end

  resource :user, only: [:update]

  resources :apps, only: [:index, :create, :show, :update, :destroy] do
    member do
      get 'documentation'
      get 'journal'
      get 'relations'
      put 'rebuild'
      post 'template'
      get 'compose_yml'
      get 'compose_download'
      get 'compose_export'
    end
    resources :services, only: [:index, :update, :create, :show, :destroy] do
      get 'journal', on: :member
    end
    resources :categories, only: [:update, :create, :destroy] do
      put 'remove_service', on: :member
      post 'add_service', on: :member
    end
  end

  resources :host_health, only: [:index]

  resources :service_health, only: [:show], :id => /[^\/]+/

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  mount CtlBaseUi::Engine => '/ctl-base-ui'
end

app/views/apps/_application_button_menu.html.haml
%ul.application-button-menu
  %li
    .settings-container{ data: { toggle: { class: 'expanded'} } }
      %ul.settings-menu
        %li
          = link_to 'Save as PMX Template', new_template_path(app_id: app.id), class: 'link template no-event-propagation', title: 'save template'
        %li
          = link_to 'Save As Compose YAML', '#', title: 'export', class: 'link export', data: { composePath: compose_yml_app_path(app.id), downloadPath: compose_download_app_path(app.id) }
        %li
          = link_to 'Deploy to Target', select_deployment_targets_path(resource_id: app.id, resource_type: 'App'), class: 'link deploy select-deployment-target', title: 'save template'
        %li
          = link_to 'Rebuild App', rebuild_app_path(app.id), method: :put, title: 'rebuild', class: 'link reload'
        %li
          = link_to 'Delete App', app_path(app.id), method: :delete, title: 'delete', class: 'delete'

#gistConfirmationDialog
  %h4 Just so you know, this will generate an anonymous Gist on Github.
  %p If you have sensitive information in your file, such as passwords, you may not want to do this.
  %p Would you like to proceed?
  %ul
    %li
      = link_to 'No, Cancel', '#', title: 'No, Cancel', class: 'cancel-export'
    %li
      = link_to 'Yes, export to Lorry.io', compose_export_app_path(app.id), title: 'Yes, export to Lorry.io', class: 'button-primary gist-confirm', target: '_blank'

app/views/apps/_application_service_row.html.haml
%li{ data: { id: presenter.id }, class: presenter.status }
  .service-icon
    %img{src: presenter.icon}
  = link_to presenter.name,
            presenter.service_url,
            title: 'service-details'
  .actions
    = link_to presenter.name,
              presenter.imagelayers_url,
              class: 'imagelayers-action',
              target: '_blank',
              title: 'Inspect this application on imagelayers.io'
    = link_to 'view',
              presenter.service_url,
              class: 'edit-action',
              title: 'details'
    = link_to 'delete',
              presenter.service_url,
              class: 'delete-action',
              title: 'delete',
              method: :delete

app/views/apps/_category_panel.html.haml
.category-panel
  %header
    %span.title
      = presenter.name
    .actions
      %a{href: "/apps/#{presenter.app_id}/categories/#{presenter.id}", class: 'edit-action'}
      %a{href: "/apps/#{presenter.app_id}/categories/#{presenter.id}", class: 'delete-action'}
  %ul.services
    - presenter.services.each do |service|
      = render 'application_service_row', {presenter: ServiceRowPresenter.new(service)}
  = link_to 'Add a Service', '#', class: 'button-positive add-service', title: 'add', data: {:category => presenter.id}

app/views/apps/_new_category.html.haml
.category-panel.new
  %header
    .name
      %span.title
        &nbsp;
    .actions
      = link_to 'Cancel', '#', class: 'text cancel', title: 'cancel'

app/views/apps/_relationship_view.html.haml
- app.ordered_services.each do |service|
  .relationship-panel
    %header
      = service.name
    - unless service.links.blank?
      %ul.links
        - service.links.each do |link|
          %li
            = link.service_name

app/views/apps/documentation.html.haml
#post-run-html= @app.documentation_to_html.html_safe

app/views/apps/index.html.haml
- content_for(:title, 'My Applications')
- content_for(:body_id, 'manage_flow')

= render '/shared/breadcrumbs', breadcrumbs: [ 'Manage',
                                                link_to('Dashboard', dashboard_index_path),
                                                yield(:title)]
%section.applications
  - @apps.each do |app|
    %div.application
      .name
        = link_to app.name, app_path(app.id)
      .info
        = link_to app.name, app.imagelayers_url, target: '_blank', title: 'View this application on imagelayers.io', class: 'imagelayers-link'
        %span
          %b
            = app.services.length
          = app.service_count_label

      .actions
        = render 'application_button_menu', app: app

  .select-target-container
    .select-target{ data: { toggle: { class: 'expanded' } } }
      %header
        Create a New Application
      .target-options
        %ul
          %li
            = link_to 'From a Template or Image', new_search_path, data: { passthru: true }
          %li
            = link_to 'From a Docker Compose YAML', '#', class: 'compose-import'

  #app-from-compose-modal
    #tabs
      %ul
        %li
          %a{ href: '#import-upload' } Import from File
        %li
          %a{ href: '#import-uri' } Import from URI
      %p
        If you have an existing YAML you'd like to run as a Panamax application, you can upload a docker-compose.yml
        or import one from a URI
      #import-upload
        %h4
          Select your local docker-compose.yml
        = form_tag({ action: :create }, multipart: true, id: 'upload-form') do
          = label_tag 'app_compose_yaml_file', 'Browse local files', class: 'button-secondary'
          %span.import-file-name
          = file_field_tag 'app[compose_yaml_file]', accept: ".yaml,.yml,text/yaml,text/x-yaml,application/yaml,application/x-yaml"
      #import-uri
        %h4
          Enter the URI to your docker-compose.yml
        = form_tag({ action: :create }, id: 'uri-form') do
          = label_tag 'app_compose_yaml_uri', 'URI:'
          = text_field_tag 'app[compose_yaml_uri]'

app/views/apps/show.html.haml
- content_for(:title, @app.name)
- content_for(:body_id, 'manage_flow')

%script#new_category_template{type: 'text/x-handlebars-template'}
  = render 'new_category'
%script#service_template{type: 'text/x-handlebars-template'}
  = render 'application_service_row', { presenter: JsonServiceRowPresenter.new() }
%script#category_archetype{type: 'text/x-handlebars-template'}
  = render 'category_panel', { presenter: JsonCategoryPresenter.new() }

%header.application
  = render '/shared/breadcrumbs', breadcrumbs: ['Manage',
                                                link_to('Dashboard', dashboard_index_path),
                                                link_to('Applications', apps_path),
                                                yield(:title)]
%section.deployment-details
  %ul.deployment-env
    %li
      %strong Deployed to:
      CoreOS Local
    %li
      =link_to('Documentation', '#', { class: 'instructions-dialog', data: { 'doc-url'=> documentation_app_path(@app.id) } })  if @app.documentation.present?
    %li
      %span{ class: 'application-access' }
        Access your application
        .context-help
          %section.tooltip
            %aside.arrow
            %span{ class: 'dismiss' }
            %p
              If your application has a GUI, map a port on your local host machine to the port bound to the CoreOS host.
            %p
              = succeed '.' do
                %a{href:'https://github.com/CenturyLinkLabs/panamax-ui/wiki/How-To%3A-Port-Forwarding-on-VirtualBox'}Go to our wiki for instructions
      = link_to("Inspect #{@app.name} on imagelayers.io", @app.imagelayers_url, title: "View #{@app.name} on imagelayers.io", target: '_blank', class:'imagelayers-link-with-text')

  = render 'application_button_menu', app: @app

%section.application-services{data: { source: app_services_path(@app.id, format: :json) } }
  %header
    %h3
      Application Services
    %nav
      %a.list.selected{ title: 'category view' }
      %a.relationship{ title: 'relationship view' }
  .views
    .categories
      - @app.categorized_services.each do |group, services|
        = render 'category_panel', { presenter: CategoryPresenter.new(@app, group, services) }
      .category-panel.add
        %header
          %span.title
            Add a Category
        %button.button-positive.add-category
    .relationships
      = render 'relationship_view', :app => @app

= render 'shared/journal',
  title: 'CoreOS Journal - Application Activity Log',
  journal_path: journal_app_path(@app.id, format: :json)

= render 'services/add_service'
#post-run-html
  = @app.documentation_to_html.html_safe if @app.documentation.present?